--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/PJZ9n/Calculator
build-by-default: true
branches:
  - master
projects:
  Calculator:
    libs:
      - src: dktapps-pm-pl/pmforms/pmforms
      - src: pjz9n/resourcepacktools/ResourcePackTools
...
